#!/usr/bin/env bash
#
# Start or stop the HTTP server that backs the QUnit suite (`grunt qunit`).
#
# Why a real server is needed at all
# ----------------------------------
# test/data/testinit.js decides
#     isLocal = window.location.protocol === "file:"
# and the suite skips every network test when isLocal is true, so the pages
# have to be fetched over http://. 86 assertions in test/unit/ajax.js -- plus
# some in support.js and manipulation.js -- request .php endpoints under
# test/data/, so the server also has to execute PHP.
#
# Why not `php -S`
# ----------------
# PHP's built-in server cannot run this suite, for two independent reasons:
#
#   * It is single-threaded before PHP 7.4 (which added
#     PHP_CLI_SERVER_WORKERS). test/data/core/dont_return.php sleeps for 30
#     seconds on purpose, and test/data/event/longLoadScript.php sleeps too;
#     either one blocks every other request while it runs. The dist/jquery.js
#     that test/data/core/dynamic_ready.html loads while dont_return.php is
#     still in flight would never arrive, and "core - document ready when
#     jQuery loaded asynchronously (#13655)" would fail on its own 10s
#     timeout.
#   * It never sends a Date response header, so both assertions in
#     "ajax - jQuery.ajax() - HEAD requests" fail.
#
# Apache with mod_php fixes both: mod_php forces the prefork MPM, so requests
# are served by separate processes, and Apache dates every response. Ubuntu
# 12.04 (Travis's `dist: precise`) ships Apache 2.2 with libapache2-mod-php5;
# newer boxes ship 2.4. The generated vhost below is written to load on both.
#
# Usage:  test/manage-test-server.sh start|stop|check
#         JQUERY_TEST_PORT overrides the port (default 8000; keep it in sync
#         with the qunit task's `urls` option in Gruntfile.js).

set -euo pipefail

PORT="${JQUERY_TEST_PORT:-8000}"
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
CONF_NAME="jquery-test.conf"

if [ "$( id -u )" = "0" ]; then
	SUDO=""
elif command -v sudo >/dev/null 2>&1; then
	SUDO="sudo"
else
	echo "manage-test-server: need root or sudo to configure Apache" >&2
	exit 1
fi

# ---------------------------------------------------------------- discovery --

# Apache's own name and layout differ per distro; resolve them once.
find_apache() {
	if command -v apache2ctl >/dev/null 2>&1; then
		APACHECTL="apache2ctl"
	elif command -v apachectl >/dev/null 2>&1; then
		APACHECTL="apachectl"
	else
		return 1
	fi
	return 0
}

# Debian/Ubuntu include every *.conf in one of these; dropping a file in
# avoids a2ensite/a2enconf, whose accepted filenames differ between 2.2 and
# 2.4.
find_conf_dir() {
	for dir in /etc/apache2/conf-enabled /etc/apache2/conf.d; do
		if [ -d "$dir" ]; then
			CONF_DIR="$dir"
			return 0
		fi
	done
	return 1
}

install_apache() {
	echo "manage-test-server: installing apache2 + mod_php"
	$SUDO apt-get update -qq
	# php5 on precise/trusty, php7.x on anything newer; ask for whichever the
	# box actually has rather than guessing.
	for pkg in libapache2-mod-php libapache2-mod-php5 libapache2-mod-php7.0; do
		if $SUDO apt-get install -y --no-install-recommends apache2 "$pkg"; then
			return 0
		fi
	done
	echo "manage-test-server: could not install apache2 with mod_php" >&2
	return 1
}

# mod_php has to be active for the .php endpoints to execute rather than be
# served as text. The module is named php5 / php7.0 / php depending on era.
enable_mod_php() {
	if $APACHECTL -M 2>/dev/null | grep -qi "php[0-9_]*_module"; then
		return 0
	fi
	if ! command -v a2enmod >/dev/null 2>&1; then
		return 1
	fi
	for mod in $( ls /etc/apache2/mods-available/ 2>/dev/null \
		| sed -n 's/^\(php[0-9.]*\)\.load$/\1/p' ); do
		if $SUDO a2enmod "$mod"; then
			return 0
		fi
	done
	return 1
}

# -------------------------------------------------------------------- start --

write_vhost() {
	# `Require all granted` is 2.4-only and `Order/Allow` is 2.2-only; gate
	# each on mod_authz_core so one file loads on both.
	$SUDO tee "$CONF_DIR/$CONF_NAME" >/dev/null <<CONF
# Generated by test/manage-test-server.sh for the jQuery QUnit suite.
Listen $PORT

<VirtualHost *:$PORT>
	DocumentRoot $ROOT
	DirectoryIndex index.html index.php

	<Directory $ROOT>
		Options Indexes FollowSymLinks
		AllowOverride None
		<IfModule mod_authz_core.c>
			Require all granted
		</IfModule>
		<IfModule !mod_authz_core.c>
			Order allow,deny
			Allow from all
		</IfModule>
	</Directory>
</VirtualHost>
CONF
}

restart_apache() {
	# service(8) is the only start path present on both precise and modern
	# Debian derivatives; fall back to apache2ctl for bare containers with no
	# init system.
	if command -v service >/dev/null 2>&1 && $SUDO service apache2 restart; then
		return 0
	fi
	$SUDO $APACHECTL -k restart || $SUDO $APACHECTL -k start
}

wait_for_server() {
	local i
	for i in $( seq 1 60 ); do
		if curl -fsS -o /dev/null "http://localhost:$PORT/test/index.html"; then
			return 0
		fi
		sleep 1
	done
	echo "manage-test-server: server did not come up on port $PORT" >&2
	return 1
}

# Assert the three properties the suite depends on, so a CI log shows them
# rather than a wall of QUnit failures if the server is wrong.
check_server() {
	local body date_header elapsed

	echo "--- server checks on http://localhost:$PORT"

	body="$( curl -fsS "http://localhost:$PORT/test/data/name.php?name=foo" )"
	if [ "$body" != "bar" ]; then
		echo "FAIL: PHP is not executing (name.php returned '$body', want 'bar')" >&2
		return 1
	fi
	echo "ok: PHP executes (.php endpoints are interpreted)"

	date_header="$( curl -fsS -I "http://localhost:$PORT/test/data/name.html" \
		| grep -ci "^Date:" )"
	if [ "$date_header" = "0" ]; then
		echo "FAIL: no Date response header; ajax HEAD tests need one" >&2
		return 1
	fi
	echo "ok: responses carry a Date header"

	# dont_return.php sleeps 30s; a concurrent server answers a second
	# request immediately, a serial one makes it wait.
	curl -s -o /dev/null "http://localhost:$PORT/test/data/core/dont_return.php" &
	sleep 1
	elapsed="$( { time -p curl -fsS -o /dev/null \
		"http://localhost:$PORT/test/index.html" ; } 2>&1 \
		| awk '/^real/ { print int( $2 ) }' )"
	if [ "${elapsed:-99}" -gt 5 ]; then
		echo "FAIL: server is serial (blocked ${elapsed}s behind a sleeping request)" >&2
		return 1
	fi
	echo "ok: server is concurrent (unblocked request took ${elapsed}s)"
}

start_server() {
	if ! find_apache; then
		install_apache
		find_apache
	fi

	if ! find_conf_dir; then
		echo "manage-test-server: no Apache conf include dir found" >&2
		exit 1
	fi

	if ! enable_mod_php; then
		install_apache
		enable_mod_php || {
			echo "manage-test-server: mod_php unavailable" >&2
			exit 1
		}
	fi

	echo "--- resolved test server"
	$APACHECTL -v 2>&1 | head -2
	$APACHECTL -M 2>/dev/null | grep -i "php\|mpm" \
		|| echo "(could not list modules)"
	php --version 2>/dev/null | head -1 || echo "(no php CLI; mod_php is what matters)"
	echo "document root: $ROOT"
	echo "port: $PORT"

	# Apache's workers run as www-data, not as the CI user, so the checkout
	# has to be traversable by them.
	chmod -R a+rX "$ROOT" 2>/dev/null \
		|| echo "(could not relax permissions; hoping they already allow it)"

	write_vhost
	restart_apache
	wait_for_server
	check_server
}

stop_server() {
	if find_apache; then
		if command -v service >/dev/null 2>&1; then
			$SUDO service apache2 stop || echo "(apache2 was not running)"
		else
			$SUDO $APACHECTL -k stop || echo "(apache2 was not running)"
		fi
	fi
	if find_conf_dir; then
		$SUDO rm -f "$CONF_DIR/$CONF_NAME"
	fi
}

case "${1:-start}" in
	start) start_server ;;
	stop) stop_server ;;
	check) check_server ;;
	*)
		echo "usage: $0 start|stop|check" >&2
		exit 1
		;;
esac
